name: pim
description: Personal Information Manager application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: 1.1.0
  sqflite: 1.3.2+1
  path_provider: 1.6.24
  flutter_slidable: 0.5.7
  intl: 0.16.1
  image_picker: 0.6.7+14
  flutter_calendar_carousel: 1.5.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true